server:
  port: 8080
  connection-timeout: 5000

spring:
  profiles:
    active: dev
  redis:
    host: 192.168.1.11
    port: 6379
#spring:
#  datasource:
##      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
#      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=yes&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.jdbc.Driver
#      type: com.alibaba.druid.pool.DruidDataSource
##      initial-size: 10
##      min-idle: 10
##      max-active: 20
##      max-wait: 6000
##      time-between-eviction-runsMillis: 6000
##      min-evictable-idle-timeMillis: 300000
##      validation-query: select 1
##      test-while-idle: false
##      test-on-borrow: true
##      test-on-return: false
##      pool-prepared-statements: true
##      max-open-prepared-statements: 20
##      max-pool-prepared-statement-per-connection-size: 20
##      filters: stat
##      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
##      use-global-data-source-stat: true
#
#  liquibase:
#      change-log: classpath:db/db.changelog-master.xml
