apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mytest
  name: mytest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytest
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mytest
    spec:
      containers:
      - image: rulinmarulin/mytest
        name: mytest
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mytest
  name: mytest
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mytest
  type: ClusterIP
status:
  loadBalancer: {}
